apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatbot
  name: chatbot
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: chatbot
  sessionAffinity: None
  type: ClusterIP
