apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: argocd-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:argocd:argocd-sa
